Improved the way DIMEMAS_HOME is set in DimemasGUI wrapper
Change-Id: I770fbf823f3f11416a0163d5682e953f67a8dd2d

diff --git a/GUI/src/DimemasGUI.in b/GUI/src/DimemasGUI.in
--- a/GUI/src/DimemasGUI.in
+++ b/GUI/src/DimemasGUI.in
@@ -1,13 +1,20 @@
 #!/bin/sh
-export DIMEMAS_HOME=@@DIMEMASHOME@@
-export DIMEMAS_GUI_JAR=$DIMEMAS_HOME/lib/GUI/@@JARFILE@@
 
-if [ -z $DIMEMAS_HOME ] ; then
-	echo "Please set DIMEMAS_HOME to the Dimemas installation root directory"
-	exit 1
-elif ! [ -e $DIMEMAS_GUI_JAR ]; then
-	echo "Dimemas GUI 'jar' file (@@JARFILE@@) not found in the"
-	echo "$DIMEMAS_HOME/bin directory. Please check the installation"
+DIMEMAS_HOME=$(dirname $(readlink -f $0))/..
+if [ -d "$DIMEMAS_HOME/lib" ]; then
+    LIBDIR="/lib"
+elif [ -d "$DIMEMAS_HOME/lib64" ]; then
+    LIBDIR="/lib64"
+else
+    echo "$DIMEMAS_HOME/{lib|lib64} not found"
+    exit 1
+fi
+
+DIMEMAS_GUI_JAR=$DIMEMAS_HOME/$LIBDIR/GUI/dimemas-gui-5.3.4.jar
+
+if ! [ -e $DIMEMAS_GUI_JAR ]; then
+	echo "Dimemas GUI 'jar' file (@@JARFILE@@) not found"
+    echo "Check your Dimemas instalation."
 	exit 1
 fi
 
